### ISSUE TITLE
In the ruby interface, the probe functions should probably not be in the Module class.

### ISSUE THREAD

**Issue by hainesr** [hainesr/ffi-openmpt#5]
They aren't in the `module` namespace in the C interface.

**Comment by sagamusix** [comment]
Hello Robert, first off, thanks for your great effort in making libopenmpt accessible to Ruby developers. In general I would recommend you to model your OO interface as closely as possible to our C++ interface rather than the C interface to make it more consistent with libopenmpt's OO approach itself.

**Comment by hainesr** [comment]
Hello! Yes, I plan to match the C++ interface as closely as I can - while also making it "ruby-like". I have to actually wrap the C interface due to restrictions with the foreign function interface, though, which is why I'm hiding that in the `OpenMPT` and `OpenMPT::Module` objects. I'm also concerned about keeping it as performant as possible.

It's still all in a state of flux as I get various bits worked out.

Thank you for all your great work on the OpenMPT tools and libraries.
